name: Deploy via FTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          missing=0
          [ -z "${{ secrets.FTP_SERVER }}" ] && echo "::error::Missing secret: FTP_SERVER" && missing=1
          [ -z "${{ secrets.FTP_USERNAME }}" ] && echo "::error::Missing secret: FTP_USERNAME" && missing=1
          [ -z "${{ secrets.FTP_PASSWORD }}" ] && echo "::error::Missing secret: FTP_PASSWORD" && missing=1
          exit $missing

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:   ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps              # gebruik FTPS als je host dat ondersteunt
          port: 21
          local-dir: ./               # of ./dist als je buildt
          server-dir: public_html/    # pas dit pad aan naar jouw webroot
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/*.map
            **/.DS_Store
            **/README.md
            **/.env*
