name: Deploy via FTPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps             # gebruik FTPS als het kan, niet plain ftp
          port: 21
          local-dir: ./
          server-dir: public_html/
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/*.map
            **/.DS_Store
            **/README.md
            **/.env*
