name: Deploy via SCP (SSH)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Upload alles uit de repo naar je webroot
      - name: Upload via SCP
        uses: appleboy/scp-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          port: ${{ secrets.SFTP_PORT }}
          # Gebruik óf password óf key:
          password: ${{ secrets.SFTP_PASSWORD }}
          # key: ${{ secrets.SFTP_PRIVATE_KEY }}
          source: "./"                # of bijv. dist/**
          target: "public_html/"      # pas aan naar jouw webroot
          overwrite: true
          strip_components: 0
          rm: false
          # Handige excludes:
          exclude: |
            .git*
            .github/**
            node_modules/**
            **/*.map
            **/.DS_Store
            **/README.md
            **/.env*
